export { Title } from './Title/Title'
export { Pictures } from './Pictures/Pictures'
export { DragAndDrop } from './DragAndDrop/DragAndDrop'
export { ImageSelected } from './ImagenSelected/ImageSelected'
export { BoxDragAndDrop } from './BoxDragAndDrop/BoxDragAndDrop'
export { Footer } from './Footer/Footer'
